### ISSUE TITLE
Menu Not Responsive on Mobile

### ISSUE THREAD

**Issue by moneerrifai** [stackbit/stackbit-theme-fresh#11]
Hello, 

Love this theme! I am having a small issue where the site's navigation menu (the hamburger) does not respond when on a mobile device. This is happening on my personal site but it is also even happening on a fresh out-of-the-box project that was not customized at all.

Both examples below were deployed on Netlify using the Stackbit Site Builder and using Next.js static site generator. 

Steps to reproduce on my personal site:
- on a mobile device or using http://mobiletest.me, navigate to my personal site: https://www.emmarifai.com
- click on the hamburger in the upper right and go to any of the other pages
- from that page, click on the hamburger again, it will be non responsive

Steps to reproduce on a generic site that was not customized at all:
- on a mobile device or using http://mobiletest.me, navigate to https://melodic-tiger-15464.netlify.app/
- click on the hamburger in the upper right corner and go to "Contact"
- From the Contact page, try clicking on the hamburger again, it will be non responsive
(for this generic site, the Contact page seems to be the only one having that issue)

Is there anything I can change or check to fix?

**Comment by TomasBankauskas** [comment]
Hi @moneerrifai, thank you for reporting this issue. I created PR for your project with the fix. Also, this theme was updated as well.
